### ISSUE TITLE
This is old, is it still supposed to work?

### ISSUE THREAD

**Issue by jtannenba** [avaldebe/TinyI2CScanner#1]
The screen keeps going and never shows detections.  Also what is the TACT pin?  Say 1 is that pin 1 or pb1?  Doesn't seem to do anything.  Are all the i2c devices supposed to be on pb3, and pb4?

Thanks

**Comment by avaldebe** [comment]
I have not compiled this program in a while, so I do not know if it still works on with newer versions of the librarys.
Are you sure it flashed correctly?

**Comment by jtannenba** [comment]
Yes, I did only change I made was programmer usbtiny, not usbasp.  I even relearned how to use Visual Code.

**Comment by avaldebe** [comment]
The only other think I can think is the I2C lines, as there is 2 sets.
One set for the screen (software I2C, provided by the U8g2 library) and a second one for the scanner (hardware I2C, provided by the TinyWire library).

> Also what is the TACT pin?
If defined it will swap the column/row order on the display.

**Comment by jtannenba** [comment]
Thanks for your reply, I will play with it some more.  Finally got it working.  The display is better/easier to read with the -D USE_U8X8 option enabled.
